export const compiladoClientesData = [
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Leroy Merlin",
    Setor_de_Atuação: "Varejo",
    Segmento: "Materiais de construção",
    Tamanho_da_Empresa_funcionários: "10000 +",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "São Paulo",
    Site: "www.leroymerlin.com.br",
    Página_Linkedin: null,
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Qlik",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "GCP",
    Qual_Solução_de_RPA: "UI Path",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/8bb0fbde-fd33-11e8-b77b-069e4f790264",
    Obs: "Aumento de recursos alocados / Venda de nossas soluções",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 1,
    Possibilidade_de_Oportunidade: 0.98,
    Possibilidade_de_Sucesso_Alta_direção: 0.2,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.63,
    Conhecimento_da_Conta: 0.603,
    MÉDIA: 0.6826000000000001,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Petz",
    Setor_de_Atuação: "Varejo",
    Segmento: "Pet",
    Tamanho_da_Empresa_funcionários: "5001 - 10000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "São Paulo",
    Site: "https://www.petz.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/petz/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Qlik",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Snowflake",
    Qual_Solução_de_RPA: "Outro",
    Qual_Solução_em_IA: "Outro",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP e CRM",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/744fdb72-fd33-11e8-b594-069e4f790264",
    Obs: "Modernização de BI e aplicação de IA e GenIA",
    ABM_Program: "LAB (BI) Innovation (Data center), Data Driven Customer (RPA)",
    Probabilidade_de_Budet_alocado: 0.7,
    Possibilidade_de_Oportunidade: 1,
    Possibilidade_de_Sucesso_Alta_direção: 0.44,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.6,
    Conhecimento_da_Conta: 0.6479,
    MÉDIA: 0.6775800000000001,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "BO Paper",
    Setor_de_Atuação: "Indústria",
    Segmento: "Papel e Celulose",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Arapoti - PR",
    Site: "https://www.bopaper.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/bo-paper/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Pyplan",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Não identificado",
    Qual_Solução_em_Cloud: "Não identificado",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/a7ef451a-1fff-11ed-88c9-069e4f790264",
    Obs: "Antes centrada em papel para impressão, a Bo Paper teve de se reciclar diante do avanço de meios digitais, e se voltou para o mundo das embalagens",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 1,
    Possibilidade_de_Sucesso_Alta_direção: 0.38,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.7,
    Conhecimento_da_Conta: 0.546,
    MÉDIA: 0.6552,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: "ok",
    Nome_da_Empresa: "Unimed Campinas",
    Setor_de_Atuação: "Saúde",
    Segmento: "Convênios",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Campinas",
    Site: "https://www.unimedcampinas.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/unimed-campinas/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Automation Anywhere",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/9ab870fc-1092-11eb-a5c1-0630baf9dcb8",
    Obs: "Não identificado",
    ABM_Program: "Case Ops",
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.9,
    Possibilidade_de_Sucesso_Alta_direção: 0.56,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.55,
    Conhecimento_da_Conta: 0.61,
    MÉDIA: 0.654,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "TIM ",
    Setor_de_Atuação: "Telecomunicações",
    Segmento: "Telecomunicações",
    Tamanho_da_Empresa_funcionários: "10000 +",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "Rio de Janeiro",
    Site: "http://www.tim.com.br",
    Página_Linkedin: "https://www.linkedin.com/company/timbrasil/life/3ed00235-e14c-4034-ba06-9ba6e0b56e6e/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Vide Portal",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Qlik e Power BI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Outro",
    Qual_Solução_em_IA: "Data Robot",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "SAP, Salesforce",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/8814a070-fd33-11e8-be2d-069e4f790264",
    Obs: "Não identificado",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 1,
    Possibilidade_de_Oportunidade: 0.96,
    Possibilidade_de_Sucesso_Alta_direção: 0.19,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.44,
    Conhecimento_da_Conta: 0.63,
    MÉDIA: 0.6439999999999999,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "JDE",
    Setor_de_Atuação: "Indústria",
    Segmento: "Alimentício",
    Tamanho_da_Empresa_funcionários: "10000 +",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "Barueri",
    Site: "https://www.jacobsdouweegberts.com/",
    Página_Linkedin: null,
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "A verificar",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Datbricks",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/c479eda2-464b-11e9-9c4b-02ae981fbade",
    Obs: "Expandir relacionamento",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 1,
    Possibilidade_de_Oportunidade: 0.78,
    Possibilidade_de_Sucesso_Alta_direção: 0.28,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.57,
    Conhecimento_da_Conta: 0.587,
    MÉDIA: 0.6434,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Eldorado Brasil Celulose S/A",
    Setor_de_Atuação: "Indústria",
    Segmento: "Papel e Celulose",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "São Paulo - SP (Escritório)",
    Site: "http://www.eldoradobrasil.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/eldorado-brasil-celulose-e-papel/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Outro",
    Qual_Solução_de_RPA: "Outro",
    Qual_Solução_em_IA: "Outro",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP SAP",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/88bd2230-ec3c-11ec-854a-022c40d974e6",
    Obs: "A inovação é um dos direcionadores do crescimento da Eldorado Brasil e integra nossa cultura organizacional – inovar está no DNA da empresa. Nossos ambientes de trabalho acolhem e discutem as ideias e sugestões de melhoria dos nossos colaboradores, mantendo a empresa sempre na fronteira tecnológica do setor de celulose, com vocação para a liderança.\nA gestão da inovação na Eldorado é descentralizada para dar mais foco e agilidade à implementação de novas ideias, em três frentes: Operação Florestal, Operação Industrial e Logística. As melhorias e inovações implementadas nessas áreas buscam reduzir impactos ambientais, otimizar o uso de recursos naturais, aumentar a produtividade, reduzir custos operacionais, melhorar as condições de saúde e segurança de colaboradores e comunidades e, ainda, desenvolver novos produtos. Este mindset inovador garante a perenidade e o crescimento do nosso negócio, com o avanço contínuo das nossas operações no campo, na indústria e na logística.",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.9,
    Possibilidade_de_Oportunidade: 0.46,
    Possibilidade_de_Sucesso_Alta_direção: 0.58,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.6,
    Conhecimento_da_Conta: 0.6195,
    MÉDIA: 0.6319,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Prysmian",
    Setor_de_Atuação: "Energia",
    Segmento: "Cabeamento",
    Tamanho_da_Empresa_funcionários: "10000 +",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "Sorocaba",
    Site: "www.prysmian.com",
    Página_Linkedin: "https://www.linkedin.com/company/prysmian/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik e PBI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "SalesFOrce, Excel, SAP BW, ECC e 4HANA",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/790f7276-d525-11ec-82d9-0630baf9dcb8",
    Obs: " https://drive.google.com/drive/search?q=next%20steps",
    ABM_Program: "Lab e/ou Innovation",
    Probabilidade_de_Budet_alocado: 1,
    Possibilidade_de_Oportunidade: 0.34,
    Possibilidade_de_Sucesso_Alta_direção: 0.42,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.73,
    Conhecimento_da_Conta: 0.6,
    MÉDIA: 0.6180000000000001,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Kopenhagen (NIBS)",
    Setor_de_Atuação: "Indústria",
    Segmento: "Alimentício",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "Extrema",
    Site: "http://www.kopenhagen.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/grupocrm/about/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Pyplan",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Outro",
    Qual_Solução_em_Cloud: "Outro",
    Qual_Solução_de_RPA: "Outro",
    Qual_Solução_em_IA: "Outro",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP e CRM",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/cf46047a-3916-11ed-ac68-069e4f790264",
    Obs: "Expansão digital da empresa",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.5,
    Possibilidade_de_Oportunidade: 0.68,
    Possibilidade_de_Sucesso_Alta_direção: 0.35,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.8,
    Conhecimento_da_Conta: 0.65,
    MÉDIA: 0.596,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "CCR",
    Setor_de_Atuação: "Mobilidade",
    Segmento: "Infraestrura para mobilidade focada em Concessóes",
    Tamanho_da_Empresa_funcionários: "10000 +",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "São Paulo",
    Site: "www.grupoccr.com.br",
    Página_Linkedin: "https://www.linkedin.com/company/grupoccroficial/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/9338871e-fd33-11e8-848c-069e4f790264",
    Obs: "Expandir nosso squad na area de Labs e outras / Poder entregar novas soluções.",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 1,
    Possibilidade_de_Oportunidade: 0.56,
    Possibilidade_de_Sucesso_Alta_direção: 0.31,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.55,
    Conhecimento_da_Conta: 0.5349,
    MÉDIA: 0.59098,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Catupiry",
    Setor_de_Atuação: "Indústria",
    Segmento: "Alimentício",
    Tamanho_da_Empresa_funcionários: "500 - 1000",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "São Paulo",
    Site: "https://catupiry.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/laticinios-catupiry-ltda/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Qlik",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Nenhum",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Totvs",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/ab2af882-1f45-11e9-b319-022c40d974e6",
    Obs: "Modernização do BI / Implantação de Data Center / Implantação de RPA / Oportunidade de Pyplan a ser identificada",
    ABM_Program: "4DWorkshops, LAB",
    Probabilidade_de_Budet_alocado: 0.45,
    Possibilidade_de_Oportunidade: 1,
    Possibilidade_de_Sucesso_Alta_direção: 0.43,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.49,
    Conhecimento_da_Conta: 0.552,
    MÉDIA: 0.5844,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: "ok",
    Nome_da_Empresa: "Urbano Agroindustrial",
    Setor_de_Atuação: "Agroindustrial",
    Segmento: "Alimentício",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Jaraguá do Sul",
    Site: "https://www.urbano.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/urbanoalimentos",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Não identificado",
    Qual_Solução_de_RPA: "Automation Anywhere",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/4d9673d4-7f18-11ea-b667-0630baf9dcb8",
    Obs: "Não identificado",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.9,
    Possibilidade_de_Sucesso_Alta_direção: 0.25,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.6,
    Conhecimento_da_Conta: 0.5,
    MÉDIA: 0.58,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Unimed Seguros",
    Setor_de_Atuação: "Seguros",
    Segmento: "Seguros",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "São Paulo",
    Site: "https://www.segurosunimed.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/segurosunimed/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "DataRobot",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Sistemas legados",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/8375b0ea-fd33-11e8-aecf-069e4f790264",
    Obs: "Manutenção do ambiente Qlik e migração para Qlik SaaS / Apoio na cosntrução do LakeHouse / Aumento da nossa equipe de consultores / Aumentar credibilidade com o Wilson / Migrando para PBI / criando lake house com AWS",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.5,
    Possibilidade_de_Oportunidade: 1,
    Possibilidade_de_Sucesso_Alta_direção: 0.21,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.56,
    Conhecimento_da_Conta: 0.55,
    MÉDIA: 0.5640000000000001,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Grupo Santa Cruz",
    Setor_de_Atuação: "Distribuição",
    Segmento: "Distribuição de Medicamentos",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "São Paulo, Curitiba",
    Site: "https://stcruz.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/gruposc-distribui%C3%A7%C3%A3o-de-medicamentos/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Nenhum",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "SAP",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/6b04d572-fd33-11e8-9d19-069e4f790264",
    Obs: "Não identificado",
    ABM_Program: "Case Ops",
    Probabilidade_de_Budet_alocado: 0.9,
    Possibilidade_de_Oportunidade: 0.36,
    Possibilidade_de_Sucesso_Alta_direção: 0.29,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.66,
    Conhecimento_da_Conta: 0.52,
    MÉDIA: 0.546,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "DIA BRASIL",
    Setor_de_Atuação: "Varejo",
    Segmento: "Supermercados",
    Tamanho_da_Empresa_funcionários: "5001 - 10000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "São Paulo",
    Site: "DIA Supermercado | Ofertas, Economia e ClubDIA",
    Página_Linkedin: "(4) Dia Brasil Sociedade Limitada: sobre nós | LinkedIn",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Talend - TOS e Altaryx",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/8c0315fe-fd33-11e8-a047-069e4f790264",
    Obs: "Subistiitur Talend TPS pore versão paga - Em andamento./ Apoiar na migração do Qlik por Power BI - Em andamento / Aumentar nossos recursos alocados",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.7,
    Possibilidade_de_Oportunidade: 0.76,
    Possibilidade_de_Sucesso_Alta_direção: 0.27,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.48,
    Conhecimento_da_Conta: 0.516,
    MÉDIA: 0.5452,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "AFIP - Associação Fundo de Incentivo à Pesquisa",
    Setor_de_Atuação: "Pesquisa",
    Segmento: "Pesquisa científica na área da saúde",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "100 M",
    Localização_Cidade: "SÃO PAULO",
    Site: "www.afip.com.br",
    Página_Linkedin: "https://www.linkedin.com/company/afip-associacaofundodeincentivoapesquisa/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Snowflake",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/611d3ffe-fd33-11e8-85d7-069e4f790264",
    Obs: "Melhora contínua de postura do consultor - Bruno / Squad Services",
    ABM_Program: "Case Ops",
    Probabilidade_de_Budet_alocado: 0.41,
    Possibilidade_de_Oportunidade: 0.84,
    Possibilidade_de_Sucesso_Alta_direção: 0.18,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.76,
    Conhecimento_da_Conta: 0.484,
    MÉDIA: 0.5347999999999999,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Pacaembu Autopeças",
    Setor_de_Atuação: "Indústria Pesada",
    Segmento: "Industria/Automibilistica",
    Tamanho_da_Empresa_funcionários: "500 - 1000",
    Tamanho_da_Empresa_Fat_anual: "500 M",
    Localização_Cidade: "São Paulo",
    Site: "https://pabu.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/aquiepabu/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Comolatti",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Sadig",
    Qual_Solução_em_Cloud: "Não identificado",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Salesforce",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/78e76ff4-ec36-11e9-83a8-02ae981fbade",
    Obs: "- Estruturação dos dados - Arquitetura de dados/ Data Lake/ BI -  | Poc Snowflake e Qlik  |'- PyPlan em avaliação",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.4,
    Possibilidade_de_Oportunidade: 0.48,
    Possibilidade_de_Sucesso_Alta_direção: 0.23,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 1,
    Conhecimento_da_Conta: 0.5,
    MÉDIA: 0.522,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Air Products",
    Setor_de_Atuação: "Energia",
    Segmento: "Gases Industriais",
    Tamanho_da_Empresa_funcionários: "10000 +",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "São Paulo",
    Site: "http://www.airproducts.com",
    Página_Linkedin: "https://www.linkedin.com/company/air-products/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/40f92a0e-dacd-11ed-a4b5-02b0ee514bc7",
    Obs: "É uma empresa muito criteriosa para contratar terceiros, por isso preferem capacitar os colaboradores e desenvolver tudo em casa, o que na maioria das vezes, leva mais tempo do que gostariam para trazer resultados. Data estimada para março sobre o assunto IA Generativa e apresentação do gerente de TI",
    ABM_Program: "4DWorkshops",
    Probabilidade_de_Budet_alocado: 1,
    Possibilidade_de_Oportunidade: 0.46,
    Possibilidade_de_Sucesso_Alta_direção: 0.08,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.52,
    Conhecimento_da_Conta: 0.47,
    MÉDIA: 0.506,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "SKF do Brasil",
    Setor_de_Atuação: "Indústria",
    Segmento: "Manufatura",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Cajamar",
    Site: "Página inicial do Grupo SKF | SKF",
    Página_Linkedin: "SKF Group: visão geral | LinkedIn",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Snowflake",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/686cb46a-fd33-11e8-89b2-069e4f790264",
    Obs: "Aumentar o uso do Qlik / Vender solução de RPA",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.55,
    Possibilidade_de_Oportunidade: 0.58,
    Possibilidade_de_Sucesso_Alta_direção: 0.18,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.71,
    Conhecimento_da_Conta: 0.49,
    MÉDIA: 0.502,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Qualicorp",
    Setor_de_Atuação: "Seguros",
    Segmento: "Seguros",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "São Paulo",
    Site: "https://linktr.ee/Qualicorp",
    Página_Linkedin: "https://www.linkedin.com/company/qualicorp",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Power Automate",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/4ac1e826-0318-11eb-a187-0630baf9dcb8",
    Obs: "Não identificado",
    ABM_Program: "Case Ops",
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.58,
    Possibilidade_de_Sucesso_Alta_direção: 0.32,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.48,
    Conhecimento_da_Conta: 0.42,
    MÉDIA: 0.49000000000000005,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "CNU",
    Setor_de_Atuação: "Saúde",
    Segmento: "Saúde",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "500 M",
    Localização_Cidade: "São Paulo",
    Site: "https://www.centralnacionalunimed.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/unimednacional/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Tableau",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "H2O",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Sales Force e legados",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/5c0f3896-cef8-11ed-bab6-02ae981fbade",
    Obs: "Aumentar nossa equipe de consultores / Serviços H20 - RFP prevista para S2 / Expansão de outras soluçôes",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.45,
    Possibilidade_de_Oportunidade: 0.66,
    Possibilidade_de_Sucesso_Alta_direção: 0.24,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.6,
    Conhecimento_da_Conta: 0.46,
    MÉDIA: 0.48200000000000004,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "FERBASA",
    Setor_de_Atuação: "Mineração",
    Segmento: "Metalúrgica",
    Tamanho_da_Empresa_funcionários: "500 - 1000",
    Tamanho_da_Empresa_Fat_anual: "200 M",
    Localização_Cidade: "Pojuca - BA",
    Site: "https://www.ferbasa.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/ferbasa/?originalSubdomain=br",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Nenhum",
    Qual_Solução_de_RPA: "Automation Anywhere",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP Progress Datasul e SQL Protheus, e documentos tipo excel, csv e txt.",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/72423802-fd33-11e8-85d6-069e4f790264",
    Obs: null,
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.38,
    Possibilidade_de_Oportunidade: 0.66,
    Possibilidade_de_Sucesso_Alta_direção: 0.05,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.84,
    Conhecimento_da_Conta: 0.468,
    MÉDIA: 0.4796,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Predilecta Alimentos",
    Setor_de_Atuação: "Indústria",
    Segmento: "Alimentício",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Matão - SP",
    Site: "https://www.predilecta.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/predilecta-alimentos/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Não identificado",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "SAP",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/609cf0e2-fd33-11e8-8df8-069e4f790264",
    Obs: " - Automatizar processos Power Automate\n- Consultoria em Qlik",
    ABM_Program: "Case Ops, Data Driven Customer, LAB de automação",
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.9,
    Possibilidade_de_Sucesso_Alta_direção: 0.33,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.46,
    MÉDIA: 0.4680000000000001,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Guarany",
    Setor_de_Atuação: "Indústria Pesada",
    Segmento: "Fabricação de Máquinas e Equipamentos para agricultura em geral",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "100 M",
    Localização_Cidade: "ITU ",
    Site: "http://www.guaranyind.com.br",
    Página_Linkedin: "https://www.linkedin.com/company/guarany-ind-stria-&-com-rcio-ltda/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "AWS e Azure",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Nenhum",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "CRM, ERP e Planilhas",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/68d368fe-fd33-11e8-bfe1-069e4f790264",
    Obs: "Realizaram o ROADMAP no final de 2023, quando atualizaram o ERP, migrando para uma versão mais atual e aderiram ao AMP da Qlik. Estou com previsão para falar sobre as iniciativas  na próxima semana, onde discutiremos também sobre RPA",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.31,
    Possibilidade_de_Oportunidade: 0.66,
    Possibilidade_de_Sucesso_Alta_direção: 0.14,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.73,
    Conhecimento_da_Conta: 0.47,
    MÉDIA: 0.4619999999999999,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Grupo Comolatti",
    Setor_de_Atuação: "Automotivo",
    Segmento: "Automotivo",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "São Paulo",
    Site: "http://www.comolatti.com.br",
    Página_Linkedin: "https://www.linkedin.com/company/comolatti-grupo/about/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Nenhum",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Progress desenvolvimento interno",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/a92208be-c99f-11e9-aba9-02ae981fbade",
    Obs: "Construção do Data Lake",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.5,
    Possibilidade_de_Oportunidade: 0.38,
    Possibilidade_de_Sucesso_Alta_direção: 0.36,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.6,
    Conhecimento_da_Conta: 0.446,
    MÉDIA: 0.4572,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Bom Futuro",
    Setor_de_Atuação: "Agroindustrial",
    Segmento: "Alimentício",
    Tamanho_da_Empresa_funcionários: "5001 - 10000",
    Tamanho_da_Empresa_Fat_anual: "5 B +",
    Localização_Cidade: "Cuiabá",
    Site: "https://www.bomfuturo.com.br/pt-br",
    Página_Linkedin: "https://www.linkedin.com/company/bomfuturooficial/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Oracle",
    Qual_Solução_de_RPA: "Power Automate",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Replicate da Qlik",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Totvs ",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/846e4fb6-fd33-11e8-80a6-069e4f790264",
    Obs: null,
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.95,
    Possibilidade_de_Oportunidade: 0.72,
    Possibilidade_de_Sucesso_Alta_direção: 0.12,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.495,
    MÉDIA: 0.457,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Tokio Marine",
    Setor_de_Atuação: "Seguros",
    Segmento: "Seguros",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "São Paulo",
    Site: "https://www.tokiomarine.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/tokio-marine-seguradora-s-a/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Power Automate",
    Qual_Solução_em_IA: "Data Robot",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/22c8b196-e969-11eb-b7a5-02ae981fbade",
    Obs: "Não identificado",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.34,
    Possibilidade_de_Sucesso_Alta_direção: 0.4,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.48,
    Conhecimento_da_Conta: 0.4,
    MÉDIA: 0.454,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Elo Serviços",
    Setor_de_Atuação: "Financeiro",
    Segmento: "Tecnologia de pagamentos",
    Tamanho_da_Empresa_funcionários: "51 - 200",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Alphavile",
    Site: "https://www.elo.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/cart%C3%A3o-elo/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Tableau",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Oracle",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/760fad84-fd33-11e8-a58a-069e4f790264",
    Obs: "IA",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.38,
    Possibilidade_de_Oportunidade: 0.68,
    Possibilidade_de_Sucesso_Alta_direção: 0.23,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.48,
    Conhecimento_da_Conta: 0.439,
    MÉDIA: 0.4418,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "CAMPARI",
    Setor_de_Atuação: "Varejo",
    Segmento: "Bebidas",
    Tamanho_da_Empresa_funcionários: "5001 - 10000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "São Paulo",
    Site: "https://www.campari.com/pt-br/",
    Página_Linkedin: "https://www.linkedin.com/company/campari-group/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Power Automate",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "SAP HANA",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/34a3f15a-387c-11ee-ba6d-02b0ee514bc7",
    Obs: "Reduzir a frequência de erros humanos / Reduzir o tempo gasto nos processos  / Reduzir esforço para encontrar dados e realizar análises",
    ABM_Program: "Atualmente a Campari não tem gestão a vista, usam muito planilha e cada area tem seus criterios de graficos e informaçies, de acordo com Cintia precisa potencializar o uso e aplicar uma gestão a vista. / O Ambiente da Campari é internacioanal pela AWS, em 2021 os dados da Campari foram invadidos causando um prejuizo de tempo e informações, porém conseguiram recuperar e hoje tudo tem que ser validado e permitido pelo o ambiente internacional. / Principais objetivos da Campari, na redução de 4 processos: Reduzir a frequência de erros humanos\nReduzir o tempo gasto nos processos\nReduzir esforço para encontrar dados e realizar análises\nProcessos: Análises de notas fiscais. - - Planejamento de incentivos tributários- Geração de visualizações sobre Prorrogação de boletos. -- Análise de ativos. / ",
    Probabilidade_de_Budet_alocado: 0.7,
    Possibilidade_de_Oportunidade: 0.62,
    Possibilidade_de_Sucesso_Alta_direção: 0.13,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.28,
    Conhecimento_da_Conta: 0.4575,
    MÉDIA: 0.4375,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Aramis",
    Setor_de_Atuação: "Varejo",
    Segmento: "Vestuário",
    Tamanho_da_Empresa_funcionários: "500 - 1000",
    Tamanho_da_Empresa_Fat_anual: "500 M",
    Localização_Cidade: "São Paulo",
    Site: "https://www.aramis.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/aramis/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik/PowerBI",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Desenvolvimento de terceiro",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "DataBricks",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Links",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/f152ba68-7090-11eb-85fa-02ae981fbade",
    Obs: "Oportunidade em SnowGraph e seviços em Power BI",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.4,
    Possibilidade_de_Oportunidade: 0.46,
    Possibilidade_de_Sucesso_Alta_direção: 0.33,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.52,
    Conhecimento_da_Conta: 0.44,
    MÉDIA: 0.43000000000000005,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "SMC Automação",
    Setor_de_Atuação: "Indústria",
    Segmento: "Tecnologia em comunicação",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "500 M",
    Localização_Cidade: "São Bernardo do Campo",
    Site: "https://smcbr.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/smc-automacao-do-brasil/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Nenhum",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "TOTVS",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/b814ffd0-d4c0-11e9-9851-02ae981fbade",
    Obs: "Expand de licenças e serviços em Qlik",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.35,
    Possibilidade_de_Oportunidade: 0.38,
    Possibilidade_de_Sucesso_Alta_direção: 0.36,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.64,
    Conhecimento_da_Conta: 0.42,
    MÉDIA: 0.43,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Mineração Caraiba (EroBrasil)",
    Setor_de_Atuação: "Mineração",
    Segmento: "Metalúrgica",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "São Paulo",
    Site: "https://erobrasil.com/",
    Página_Linkedin: "https://www.linkedin.com/company/ero-brasil/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Power Automate",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Protheus",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/5d9128c8-fd33-11e8-9ced-069e4f790264",
    Obs: "Data Lake",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.14,
    Possibilidade_de_Sucesso_Alta_direção: 0.17,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.6,
    Conhecimento_da_Conta: 0.399,
    MÉDIA: 0.39180000000000004,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Maisativo (Superbid)",
    Setor_de_Atuação: "Leilões",
    Segmento: "Leilões",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "São Paulo",
    Site: "http://www.superbid.net",
    Página_Linkedin: "https://www.linkedin.com/company/superbid/about/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Outro",
    Qual_Solução_de_RPA: "Outro",
    Qual_Solução_em_IA: "Outro",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/832df78c-fd33-11e8-987d-069e4f790264",
    Obs: "Estruturação do Data Lake / IA",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.4,
    Possibilidade_de_Oportunidade: 0.34,
    Possibilidade_de_Sucesso_Alta_direção: 0.32,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.48,
    Conhecimento_da_Conta: 0.37,
    MÉDIA: 0.382,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "UNIMED SJRP",
    Setor_de_Atuação: "Saúde",
    Segmento: "Saúde",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "200 M",
    Localização_Cidade: "São José do Rio Preto - SP",
    Site: "https://www.unimedriopreto.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/unimedriopreto/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "WDG IBM",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Azure Fabric 2.0",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "ERP TOTVS, Banco SQL, csv, excel, txt.",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/5efbe3a6-fd33-11e8-92f2-069e4f790264",
    Obs: null,
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.33,
    Possibilidade_de_Oportunidade: 0.34,
    Possibilidade_de_Sucesso_Alta_direção: 0.05,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.59,
    Conhecimento_da_Conta: 0.3437,
    MÉDIA: 0.33074000000000003,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Wittel Comunicações",
    Setor_de_Atuação: "Tecnologia",
    Segmento: "Tecnologia em comunicação",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "100 M",
    Localização_Cidade: "São Paulo",
    Site: "http://www.wittel.com",
    Página_Linkedin: "https://www.linkedin.com/company/wittel-comunicacoes/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Azure",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/143ad234-59ee-11ed-966a-02ae981fbade",
    Obs: "Não identificado",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.31,
    Possibilidade_de_Oportunidade: 0.34,
    Possibilidade_de_Sucesso_Alta_direção: 0,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.66,
    Conhecimento_da_Conta: 0.32,
    MÉDIA: 0.326,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Cassol Centerlar",
    Setor_de_Atuação: "Varejo",
    Segmento: "Materiais de construção",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Kobrasol - SC",
    Site: "https://www.cassol.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/cassol-centerlar/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "GCP",
    Qual_Solução_de_RPA: "Outro/ Python",
    Qual_Solução_em_IA: "Iniciativas locais apenas",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Pentaho",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Salesforce",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/9d779a5a-bf61-11ec-9be4-022c40d974e6",
    Obs: "IA / Análise 360 do cliente",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.65,
    Possibilidade_de_Oportunidade: 0.34,
    Possibilidade_de_Sucesso_Alta_direção: 0.29,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.348,
    MÉDIA: 0.3256,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "IATEC",
    Setor_de_Atuação: "Tecnologia",
    Segmento: "Comunicação e Artes",
    Tamanho_da_Empresa_funcionários: "201 - 500",
    Tamanho_da_Empresa_Fat_anual: "2 B",
    Localização_Cidade: "Hortolãndia-SP",
    Site: "https://iatec.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/iatecoficial/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "AWS",
    Qual_Solução_de_RPA: "Nenhum",
    Qual_Solução_em_IA: "Open AI",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Desenvolvimeno Interno",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/dbfe325a-1a5d-11ed-8d81-02b0ee514bc7",
    Obs: "AI",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0,
    Possibilidade_de_Oportunidade: 0.32,
    Possibilidade_de_Sucesso_Alta_direção: 0.38,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0.52,
    Conhecimento_da_Conta: 0.343,
    MÉDIA: 0.3126,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "ALD Automotive",
    Setor_de_Atuação: "Automotivo",
    Segmento: "Gestão Frota Veículos",
    Tamanho_da_Empresa_funcionários: "5001 - 10000",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "São Paulo",
    Site: "https://www.aldautomotive.com.br/",
    Página_Linkedin: "https://www.linkedin.com/company/ald-automotive/",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "Azure e AWS",
    Qual_Solução_de_RPA: "Power Automate",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Sim",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Salesforce",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/6e2ff948-fd33-11e8-8fe4-069e4f790264",
    Obs: "Avaliação de novos serviços em Engenharia de dados",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.55,
    Possibilidade_de_Oportunidade: 0.38,
    Possibilidade_de_Sucesso_Alta_direção: 0.29,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.32,
    MÉDIA: 0.308,
  },
  {
    Serviço_Grupo_IN: "Sim",
    Licença_Grupo_IN: "Não",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Consórcio Scania",
    Setor_de_Atuação: "Financeiro",
    Segmento: "Consórcios",
    Tamanho_da_Empresa_funcionários: "1001 - 5000",
    Tamanho_da_Empresa_Fat_anual: "1 B",
    Localização_Cidade: "São Bernardo do Campo",
    Site: "https://solucoesscania.com.br/solucoes-financeiras/consorcio-scania/",
    Página_Linkedin: "https://www.linkedin.com/company/scania-latinamerica/?originalSubdomain=br",
    Temos_Case: "Sim",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não Mapeado",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Power BI",
    Qual_Solução_em_Cloud: "Nenhum",
    Qual_Solução_de_RPA: "Automation Anywhere",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "crm não tem  \nerp Outbank/Consórcio Newcom",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/6af1426e-fd33-11e8-a380-069e4f790264",
    Obs: "Estruturação dos dados",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.5,
    Possibilidade_de_Oportunidade: 0.58,
    Possibilidade_de_Sucesso_Alta_direção: 0,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.299,
    MÉDIA: 0.2758,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "Unimed Goiania",
    Setor_de_Atuação: "Saúde",
    Segmento: "Saúde",
    Tamanho_da_Empresa_funcionários: "500 - 1000",
    Tamanho_da_Empresa_Fat_anual: "500 M",
    Localização_Cidade: "Goiana",
    Site: "https://www.unimedgoiania.coop.br/wps/portal/internet/!ut/p/z1/04_Sj9CPykssy0xPLMnMz0vMAfIjo8ziDSy8jQydgw18LVzCDA0cXczNAlzNgj08DQ30wwkpiAJJ4wCOIP1RhJQU5EYYpDsqKgIAIbkEkg!!/dz/d5/L2dBISEvZ0FBIS9nQSEh/",
    Página_Linkedin: "https://www.linkedin.com/company/unimedgoiania/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Temos cases de RPA e H20, soluções de interesse, como também se serviçoes e liceniamento Qlik",
    Case_do_Fabricante_ou_similar: "Sim",
    Qual_Solução_de_DataViz: "Tableau",
    Qual_Solução_em_Cloud: "Outro",
    Qual_Solução_de_RPA: "Nenhum (Em fase de POC)",
    Qual_Solução_em_IA: "Nenhum",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Oracle",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/019b1506-a4d0-11ea-b4f8-022c40d974e6",
    Obs: "Tem a solução Perpetua da QLik com a IN, mas a principal é a Tableau/ Data Center, compraram recetimemte, acreditmos que nos proximimos 5 anos não migrarão para nuvem. ",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.4,
    Possibilidade_de_Oportunidade: 0.48,
    Possibilidade_de_Sucesso_Alta_direção: 0.13,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.318,
    MÉDIA: 0.2656,
  },
  {
    Serviço_Grupo_IN: "Não",
    Licença_Grupo_IN: "Sim",
    Alinhamento_interno: null,
    Nome_da_Empresa: "FITINSUR",
    Setor_de_Atuação: "Seguros",
    Segmento: "Insurtech as a Service",
    Tamanho_da_Empresa_funcionários: "11 - 50",
    Tamanho_da_Empresa_Fat_anual: "100 M",
    Localização_Cidade: "São Paulo",
    Site: "http://www.fitinsur.com",
    Página_Linkedin: "https://www.linkedin.com/company/fitinsurbrazil/",
    Temos_Case: "Não",
    Se_a_opção_ao_lado_for_Sim_ou_mais_de_uma_especifique_abaixo: "Não",
    Case_do_Fabricante_ou_similar: "Não",
    Qual_Solução_de_DataViz: "Qlik",
    Qual_Solução_em_Cloud: "Não identificado",
    Qual_Solução_de_RPA: "Não identificado",
    Qual_Solução_em_IA: "Não identificado",
    Conta_ferramenta_específica_de_Integração_de_de_Dados: "Não identificado",
    Quais_as_principais_fontes_de_dados_CRM_ERP_etc: "Não identificado",
    Conta_CRM: "https://in1.sugarondemand.com/#Accounts/156c9408-cabc-11ea-bd4e-022c40d974e6",
    Obs: "Ainda não estão muito claros, pois o responsável no assunto precisou colocar a casa em ordem durante esses 18 meses que está na empresa. Estamos marcando uma visita para tratarmos melhor do assunto.",
    ABM_Program: null,
    Probabilidade_de_Budet_alocado: 0.06,
    Possibilidade_de_Oportunidade: 0.12,
    Possibilidade_de_Sucesso_Alta_direção: 0.19,
    Possibilidade_de_Sucesso_Contatos_estratégicos: 0,
    Conhecimento_da_Conta: 0.09,
    MÉDIA: 0.092,
  },
];
